import {useMemo,useState} from 'react';import {useSearchParams} from 'react-router-dom';import {Activity,AlertTriangle,Clock,PenLine,Search,UserCog,X} from 'lucide-react';
import {Empty,PageTitle,Status} from '../components/common';
import {FlowCanvas} from '../components/FlowCanvas';
import {useAppStore,resolveApprover} from '../store/useAppStore';
import {managers} from '../../mock-data/catalog';
export function Monitor(){const ins=useAppStore(s=>s.instances),ws=useAppStore(s=>s.workflows),delegations=useAppStore(s=>s.delegations),sign=useAppStore(s=>s.signApproval),[params]=useSearchParams();const [filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(params.get('instance'));const rows=useMemo(()=>ins.filter(i=>filter==='all'||i.status===filter),[ins,filter]);const item=ins.find(i=>i.id===selected),flow=ws.find(w=>w.id===item?.workflowId);
 const pending=item?.timeline.find(t=>t.kind==='approval'&&t.status!=='completed');
 const resolution=useMemo(()=>item&&pending?resolveApprover(delegations,managers[item.applicant]||item.applicant,item.domain):null,[delegations,item,pending]);
 return <div className="page"><PageTitle eyebrow="运行中心" title="Runtime Monitor" desc="观察流程实例状态、耗时和风险，快速定位异常节点。"/><section className="monitor-kpis">{[['运行中',ins.filter(i=>i.status==='running').length,Activity],['异常',ins.filter(i=>i.status==='abnormal').length,AlertTriangle],['超时',ins.filter(i=>i.status==='timeout').length,Clock],['今日完成',ins.filter(i=>i.status==='completed').length,Activity]].map(([a,b,I]:any)=><article key={a}><I/><span><small>{a}</small><b>{b}</b></span></article>)}</section><div className="toolbar panel"><div className="search"><Search/><input placeholder="搜索实例或申请人"/></div>{[['all','全部'],['abnormal','异常'],['timeout','超时'],['running','进行中'],['completed','已完成']].map(([v,l])=><button key={v} className={'filter '+(filter===v?'active':'')} onClick={()=>setFilter(v)}>{l}</button>)}</div><section className="panel monitor-table"><table><thead><tr><th>实例编号</th><th>申请人</th><th>业务域</th><th>当前节点</th><th>状态</th><th>提交时间</th><th>耗时</th><th>风险</th></tr></thead><tbody>{rows.map(i=><tr key={i.id} data-testid="instance-row" onClick={()=>setSelected(i.id)}><td><b>{i.id}</b></td><td>{i.applicant}</td><td>{i.domain}</td><td>{i.currentNode}</td><td><Status value={i.status}/></td><td>{i.submittedAt}</td><td>{i.duration}</td><td><Status value={i.risk}/></td></tr>)}</tbody></table></section>{item&&flow&&<div className="drawer-backdrop"><aside className="instance-drawer" data-testid="instance-detail"><div className="drawer-head"><div><small>流程实例详情</small><h2>{item.id}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)}><X/></button></div><div className="detail-meta"><div><small>申请人</small><b>{item.applicant}</b></div><div><small>状态</small><Status value={item.status}/></div><div><small>耗时</small><b>{item.duration}</b></div><div><small>风险</small><Status value={item.risk}/></div></div>
 {resolution&&<div className={'assignment-card '+(resolution.approver!==resolution.nominal?'delegated':'')} data-testid="assignment-card"><div className="assignment-head"><UserCog/><b>当前人工审批 · {pending!.title}</b></div><div className="assignment-body"><div><small>名义审批人</small><b>{resolution.nominal}</b></div>{resolution.chain.length>0&&<div className="assignment-chain" data-testid="assignment-chain">{resolution.chain.map((d,k)=><span key={d.id}>{k===0?d.delegator:resolution.chain[k-1].delegate}<i>→</i>{d.delegate}</span>)}</div>}<div className="actual"><small>实际代办人</small><b data-testid="pending-handler">{resolution.approver}</b>{resolution.approver!==resolution.nominal&&<em>委托生效中</em>}</div><button data-testid="sign-approval" onClick={()=>sign({instanceId:item.id,title:pending!.title,handler:resolution.approver,via:resolution.nominal})}><PenLine/>代为审批通过</button></div></div>}
 <h3>执行流程</h3><div className="runtime-canvas"><FlowCanvas nodes={flow.nodes} edges={flow.edges} onNodes={()=>{}} onEdges={()=>{}} onSelect={()=>{}} highlight={flow.nodes.find(n=>n.data.label===item.currentNode)?.id}/></div><h3>执行时间线</h3><div className="timeline" data-testid="execution-timeline">{item.timeline.map(t=><div key={t.title} className={t.status}><i/><span><b>{t.title}</b>{t.kind==='approval'&&(t.signedBy?<small className="signer" data-testid="signed-record">签字人：{t.signedBy}{t.signedVia&&t.signedVia!==t.signedBy&&<>（代 {t.signedVia}）<em className="frozen">签字已固化</em></>}</small>:<small className="signer pending-signer">{resolution?<>待 {resolution.approver} 处理{resolution.approver!==resolution.nominal&&<>（代 {resolution.nominal}）</>}</>:'待处理'}</small>)}<small>{t.time}</small></span><Status value={t.status}/></div>)}</div></aside></div>}</div>}
