import {useMemo,useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {ArrowRight,ArrowLeft,Paperclip,RotateCcw,UserCog} from 'lucide-react';import {useAppStore,resolveApprover} from '../store/useAppStore';
import {currentUser,managers,users} from '../../mock-data/catalog';
export function Preview(){const nav=useNavigate(),{id}=useParams(),w=useAppStore(s=>s.workflows.find(x=>x.id===id))!,delegations=useAppStore(s=>s.delegations);const form=w.nodes.find(n=>n.type==='form'),condition=w.nodes.find(n=>n.type==='condition');const [values,setValues]=useState<Record<string,string>>({});const [applicant,setApplicant]=useState(currentUser);const amount=Number(values.amount||0),threshold=Number(condition?.data.config.value||5000),branch=amount>threshold?'高额分支：通知财务审批人':'标准分支：写入系统记录';const [submitted,setSubmitted]=useState(false);
 const resolution=useMemo(()=>resolveApprover(delegations,managers[applicant]||applicant,w.domain),[delegations,applicant,w.domain]);
 const delegated=resolution.approver!==resolution.nominal;
 return <div className="preview-page"><header className="preview-header"><button className="icon-btn" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/></button><div><b>表单预览</b><small>{w.name} · 实时分支模拟</small></div><span className="spacer"/><button className="secondary" onClick={()=>setValues({})}><RotateCcw/>重置</button><button onClick={()=>setSubmitted(true)}>模拟提交</button></header><div className="preview-stage"><section className="form-preview"><div className="form-cover"><small>{w.domain} / 申请表单</small><h1>{form?.data.label||'业务申请'}</h1><p>请完整填写以下信息，带 * 的字段为必填项。</p></div><div className="form-body"><label className="applicant-pick">预览申请人<select aria-label="预览申请人" value={applicant} onChange={e=>setApplicant(e.target.value)}>{users.map(u=><option key={u}>{u}</option>)}</select></label>{(form?.data.config.fields||[]).map((f:any)=><label key={f.id}>{f.label}{f.required&&<em>*</em>}{f.type==='attachment'?<div className="upload"><Paperclip/><b>拖入文件或点击上传</b><small>支持 PDF、DOCX、PNG，单个文件不超过 20MB</small></div>:f.type==='text'?<textarea aria-label={f.label} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} rows={5} placeholder="请输入详细说明（最多 2,000 字）"/>:<div className={f.type==='amount'?'money-input':''}>{f.type==='amount'&&<span>¥</span>}<input aria-label={f.label} type={f.type==='amount'||f.type==='number'?'number':f.type==='date'?'date':'text'} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} placeholder={f.type==='amount'?'0.00':'请输入'}/></div>}{submitted&&f.required&&!values[f.id]&&<small className="field-error">此字段为必填项</small>}</label>)}</div></section><aside className="simulation"><h3>条件分支模拟</h3><p>表单字段变化会实时计算流程走向。</p><div className="sim-rule"><small>当前规则</small><b>申请金额 &gt; ¥{threshold.toLocaleString()}</b></div><div className={'sim-result '+(amount>threshold?'high':'normal')} data-testid="branch-result"><small>模拟结果</small><b>{branch}</b><p>当前输入：¥{amount.toLocaleString(undefined,{minimumFractionDigits:2})}</p></div>
 <div className={'approver-card '+(delegated?'delegated':'')} data-testid="approver-resolution">
  <div className="approver-card-head"><UserCog/><small>人工审批归属</small></div>
  <div className="approver-line"><span>名义审批人</span><b>{resolution.nominal}</b></div>
  {delegated&&<div className="approver-chain" data-testid="delegation-chain">{resolution.chain.map((d,k)=><span className="chain-hop" key={d.id}><i>{k===0?d.delegator:resolution.chain[k-1].delegate}<ArrowRight/>{d.delegate}</i><small>{d.reason}</small></span>)}</div>}
  <div className="approver-line actual"><span>实际代办人</span><b data-testid="actual-approver">{resolution.approver}</b>{delegated&&<em>委托生效中</em>}</div>
 </div>
 <div className="sim-path"><span className="done">提交申请</span><i>↓</i><span className="done">直属主管审批</span><i>↓</i><span className="active">{amount>threshold?'高额通知':'记录系统'}</span></div></aside></div></div>}
